using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace mywebapp.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS public.notes (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    title character varying(255) NOT NULL,
                    content text NOT NULL,
                    created_at timestamp with time zone NOT NULL DEFAULT now()
                );

                DO $$
                BEGIN
                    IF to_regclass('public."Notes"') IS NOT NULL THEN
                        INSERT INTO public.notes (title, content, created_at)
                        SELECT old_notes."Title", old_notes."Content", old_notes."CreatedAt"
                        FROM public."Notes" AS old_notes
                        WHERE NOT EXISTS (
                            SELECT 1
                            FROM public.notes AS new_notes
                            WHERE new_notes.title = old_notes."Title"
                              AND new_notes.content = old_notes."Content"
                              AND new_notes.created_at = old_notes."CreatedAt"
                        );
                    END IF;
                END $$;

                CREATE INDEX IF NOT EXISTS ix_notes_created_at ON public.notes (created_at);
                CREATE INDEX IF NOT EXISTS ix_notes_title ON public.notes (title);
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP INDEX IF EXISTS public.ix_notes_title;
                DROP INDEX IF EXISTS public.ix_notes_created_at;
                DROP TABLE IF EXISTS public.notes;
                """);
        }
    }
}
